blogging/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myblog.urls',namespace='myblog')),
    
    #path('account/',include('accounts.urls',namespace='accounts'))
]

# if settings.DEBUG:
#     urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import path,re_path,include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from .views import(
	blog_home,
	blog_create,
	blog_delete,
	blog_update,
	blog_detail,
	BlogSitemap,
	tag_view,
	
	)
sitemaps = {
    'static': BlogSitemap,
}
app_name='posts'
urlpatterns=[
   path('',blog_home,name="home"),
   path('create/',blog_create,name='create'),
   re_path(r'^(?P<slug>[\w-]+)/edit/$',blog_update,name='update'),
   re_path(r'^(?P<slug>[\w-]+)/delete/$',blog_delete,name='delete'),
   re_path(r'^(?P<slug>[\w-]+)/$',blog_detail,name='detail'),
   path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
   re_path(r'^tag/(?P<slug>[\w-]+)/$',tag_view,name='tag_view')
   


]

myblog/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType
from .utils import get_read_time
from meta.models import ModelMeta
from mptt.models import MPTTModel, TreeForeignKey,TreeManyToManyField

# Create your models here.
class PostManager(models.Manager):
	def active(self,*args,**kwargs):
		return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())
def upload_location(instance,filename):
	return "%s/%s"%(instance.id,filename)#if we want to save in user folder then change id to user



class Tag(models.Model):
	tag=models.CharField(max_length=50)
	def __str__(self):
		return self.tag
class Post(ModelMeta,models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.DO_NOTHING)
	title = models.CharField(max_length=150)
	slug=models.SlugField(unique=True)
	image=models.ImageField(upload_to=upload_location,null=True,blank=True,width_field="width_field",height_field="height_field")
	height_field=models.IntegerField(default=0)
	width_field=models.IntegerField(default=0)
	draft=models.BooleanField(default=False)
	publish=models.DateField(auto_now=False,auto_now_add=False)
	content = models.TextField()
	tag=models.ManyToManyField(Tag,blank=True,related_name='posttag')
	updated=models.DateTimeField(auto_now=True,auto_now_add=False)
	read_time=models.IntegerField(default=0)
	timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)

	objects=PostManager()
	_metadata = {
		'description': 'content',		
	}
	def get_meta_image(self):
		if self.image:
			return self.image.url


	def __str__(self):
		return self.title
	def get_markdown(self):
		content=self.content
		markdown_text=markdown(content)
		return mark_safe(markdown_text)


	def get_absolute_url(self):
		return reverse("posts:detail",kwargs={"slug":self.slug})

	# @property
	# def comments(self):
	# 	instance=self
	# 	qs=Comment.objects.filter_by_instance(instance)
	# 	return qs
	
	@property
	def get_content_type(self):
		instance=self
		content_type=ContentType.objects.get_for_model(instance.__class__)
		return content_type

def create_slug(instance,new_slug=None):
	slug=slugify(instance.title)
	if new_slug is not None:
		slug=new_slug
	qs=Post.objects.filter(slug=slug).order_by("-id")
	exists=qs.exists()
	if exists:
		new_slug="%s-%s"%(slug,qs.first().id)
		return create_slug(instance,new_slug=new_slug)
	return slug

def pre_save_post_reciever(sender,instance,*args,**kwargs):
	if not instance.slug:
		instance.slug=create_slug(instance)
	if instance.content:
		html_string=instance.get_markdown()
		read_time_var=get_read_time(html_string)
		instance.read_time=read_time_var
	




pre_save.connect(pre_save_post_reciever,sender=Post)

myblog/forms.py
from django import forms 

from .models import *
from pagedown.widgets import PagedownWidget
class PostForm(forms.ModelForm):
	content=forms.CharField(widget=PagedownWidget(show_preview=False))
	publish=forms.DateField(widget=forms.SelectDateWidget)
	tag=forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Tag.objects.all())
	class Meta:
		
		model=Post
		fields=["title","content","image","draft","publish","tag"]

myblog/views.py
from urllib.parse import quote_plus
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Tag
from .forms import PostForm
from django.http import HttpResponseRedirect,Http404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render
from django.utils import timezone
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.contrib.sitemaps import Sitemap

# Create your views here.
def tag_view(request,slug=None):
	tag=get_object_or_404(Tag,tag=slug)
	return render(request,'blog/tagdetail.html',{'tags':tag})

def blog_home(request):
	tag=Tag.objects.all()
	today=timezone.now().date()
	queryset_list=Post.objects.active().order_by("-timestamp")
	if request.user.is_staff or request.user.is_staff:
		queryset_list=Post.objects.all().order_by("-timestamp")
	query=request.GET.get('q')
	if query:
		queryset_list=queryset_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(user__first_name__icontains=query)|
			Q(user__last_name__icontains=query)
			).distinct()
	paginator = Paginator(queryset_list, 3) # Show 25 contacts per page
	page_request_var="page"

	page = request.GET.get(page_request_var)
	queryset = paginator.get_page(page)
	 
	context={"title":"This is the title",
	"object":queryset,
	"page_request_var":page_request_var,
	"today":today,
	'tags':tag



	}
	return render(request,'blog/home.html',context)



def blog_create(request):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	form = PostForm(request.POST or None,request.FILES or None)
	if form.is_valid():
	    instance = form.save(commit=False)
	    instance.user=request.user #i gonna assume that user is logged in
	    instance.save()
	    form.save_m2m()
	    return HttpResponseRedirect(instance.get_absolute_url())
	elif form.errors:
	    messages.error(request, "Not Successfully Created")
	else:
	    pass
	
	context={
	"form":form
	}
	return render(request,'blog/forms.html',context)
	
def blog_update(request,slug=None):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance=get_object_or_404(Post,slug=slug)
	form=PostForm(request.POST or None,request.FILES or None,instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
		messages.success(request,"Updated Successfully")
		return HttpResponseRedirect(instance.get_absolute_url())
	context={"title":instance.title,
	'instance':instance,
	"form":form 

	}
	return render(request,'blog/forms.html',context)

def blog_delete(request,slug=None):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance=get_object_or_404(Post,slug=slug)
	instance.delete()
	messages.success(request,"Successfully deleted")
	return redirect("myblog:home")


def blog_detail(request,slug=None):
	instance=get_object_or_404(Post,slug=slug)
	if instance.draft or instance.publish>timezone.now().date():
		if not (request.user.is_staff or request.user.is_superuser):
			raise Http404
		
	share_string=quote_plus(instance.content)
	initial_data={
	"content_type":instance.get_content_type,
	"object_id":instance.id
    

	}

	queryset_list=Post.objects.all().order_by("-timestamp")

	meta= instance.as_meta()
    	
	context={"title":instance.title,
	"instance":instance,
	"share_string":share_string,
	"objects":queryset_list,
	"meta":meta,
	}
	return render(request,'blog/detail.html',context)




class BlogSitemap(Sitemap):
	changefreq = "daily"
	priority = 0.5

	def items(self):
		return Post.objects.all()




templates/base.html
{% load static %}
{% load meta %}

<!DOCTYPE html>
<html>
<head {% meta_namespaces %}>
{% include "meta/meta.html" %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">

<style type="text/css">
body, html {
     min-height: 100%;
     padding-top: 50px; 
     padding-right:10px; 
     padding-left:10px;
     padding-bottom: 20px;
}
.bg {
    /* The image used */
    background-image: url("https://mdbootstrap.com/img/Photos/Horizontal/Nature/full page/img(20).jpg");

    /* Full height */
    height: 100%;

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

html{
  position:relative; 
  min-height: 100%;
}
/*Normalize html and body elements,this style is just good to have*/
html,body{
  margin:0;
  
}
.pageContentWrapper{
  margin-bottom:100px;/* Height of footer*/
} 
.footer{
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height:100px;
    background:#ccc;
}  

</style>

	<title>Geeking</title>
{% block head_extra %}
<meta property="og:title" content="Geeking">
<meta property="og:image" content="https://s3.ap-south-1.amazonaws.com/geekingblog/media/None/coffee-smartphone-desk-pen+(1).jpg">
<meta property="og:url" content="geekingblog.herokuapp.com">
<meta property="og:site_name" content="Geeking Blog">
<meta property="og:description" content="It's hard to remember a world without blogs. Originally a sort of online journal full of mundane personal updates, web logs have morphed into an extremely">
{% endblock head_extra %}

</head>
 <body style="background-color:#D3D3D3;">
<div class=pageContentWrapper>
 <div id='header'>
<!--Navbar-->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white lighten-5">

    <!-- Navbar brand -->
<div class='container'>    
    <a class="navbar-brand px-lg-4 mr-0" href="/">Geeking</a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
     <!--    <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                <a class="nav-link" href="#"><strong>BLOG</strong>
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><strong>@nd link</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>

           
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>

        </ul> -->
        <!-- Links -->
<div class="ml-auto">

 <form class="form-inline">
            <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}" required="">
            </div>
        </form>




</div>
    </div>
    <!-- Collapsible content -->
</div>
</nav>
</div>
<!--/.Navbar-->


    <!-- <div class="bg animated fadeInDown"></div>

    <p class="py-5 text-center">This example creates a full page background image. Try to resize the browser window to see how it always will cover the full screen (when scrolled to top), and that it scales nicely on all screen sizes.</p>
 -->

<div class='body'>
  {% block content %}

  {% endblock content %}
</div>

</div>
<!-- Footer -->
<!-- Footer -->
<div class='footer'>
<footer class="page-footer font-small special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!-- Form -->
          <a class="fb-ic" href='https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}'>
              <i class="fa fa-facebook fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic" href='https://twitter.com/home?status={{share_string}}%20{{ request.build_absolute_uri }}'>
              <i class="fa fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!-- Google +-->
            <a class="gplus-ic">
              <i class="fa fa-google-plus fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Linkedin -->
            <a class="li-ic" href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}/&title={{instance.title}}&summary={{share_string}}&source={{ request.build_absolute_uri }}">
              <i class="fa fa-linkedin fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fa fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Pinterest-->
            <a class="pin-ic">
              <i class="fa fa-pinterest fa-lg white-text fa-2x"> </i>
            </a>
          <!-- Form -->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <form class="input-group">
            <input type="text" class="form-control form-control-sm" placeholder="Your email" aria-label="Your email" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-sm btn-outline-white" type="button">Sign up</button>
            </div>
          </form>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href=""> GEEKING</a>
    </div>
    <!-- Copyright -->

  </footer>
</div>

  <!-- Footer -->
<!-- JQuery -->

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js"></script>


<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.4.0/marked.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>



<script type="text/javascript">
$(document).ready(function(){
	$(".rimage img").each(function(){
			$(this).addClass("img-fluid mx-auto d-block");
		
		})

	
	var contentInput = $("#id_content");
	function setContent(value){
		var markedContent=marked(value)
		$("#preview_content").html(markedContent)
		$('#preview_content img').each(function(){
			$(this).addClass("img-fluid mx-auto d-block")
		})

	}
	setContent(contentInput.val())

	contentInput.keyup(function(){

		var newContent=$(this).val()
		setContent(newContent)

	})
	var titleInput=$("#id_title");

	function setTitle(value){
		$("#preview_title").text(value)
	}
	setTitle(titleInput.val())
	
	titleInput.keyup(function(){
		
		var newContent=$(this).val()
		setTitle(newContent)
	})

})
</script>

</body>
</html>

templates/blog/detail.html
{% extends "base.html" %}

{% block head_extra %}
<meta property="og:title" content="{{instance.title}}"/>
<meta property="og:image" content="{{instance.image}}"/>
<meta property="og:url" content="{{ request.build_absolute_uri }}"/>
<meta property="og:site_name" content="Blob Blog"/>
<meta property="og:description" content="{{instance.content}}"/>
{% endblock head_extra %}


{% block content %}
<nav class="navbar fixed-top navbar-light white lighten-4 auto">
	
	<a class="navbar-brand px-lg-4 mr-0" href="/">Geeking</a>

    <span class="navbar-brand"><strong>{{ instance.title }}</strong></span>
</nav>
<div class='row'>
<div class="col-sm-9"> 
<!-- Card -->
<div class="card card-cascade wider reverse">

  <!-- Card image -->
  <div class="view view-cascade overlay">
    {% if instance.image %}
    <img class="card-img-top" src="{{ instance.image.url }}" alt="Card image cap">
    <a href="">
      <div class="mask rgba-white-slight"></div>
    </a>
    
    {% endif %}
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>
  
  <div class="card-body card-body-cascade">

    <!-- Title -->
    <h4 class="card-title text-center"><strong>{{instance.title}}</strong></h4>
    <!-- Subtitle -->
    <hr>
  <div class='row container'>
 <div class=" mr-auto">
 	<p><i>Written by &nbsp </i><b>{{ instance.user.first_name}} {{ instance.user.last_name}} &nbsp|&nbsp </b><small> {{ instance.publish}}</small>&nbsp | {{ instance.read_time }} min read &nbsp|&nbsp {% if user.is_authenticated %}<a href="{% url 'posts:update' instance.slug %}">edit</a>{% endif %} &nbsp|&nbsp Tags:

{% for obj in instance.tag.all %}
<a href="{% url 'posts:tag_view' obj.tag %}" class="badge badge-primary">{{ obj.tag }}</a>
{% endfor %}


 	</p>
 	</div>
  {% load namify %}

 
 <div class='ml-auto'>
 
  <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" class="px-2 fa-lg fb-ic"><i class="fa fa-facebook"></i></a>
  
</div>
</div>
<hr>
    <!-- Text -->
    <div class=" rimage">{{instance.get_markdown}}
    </div>

    <!-- Linkedin -->
 <hr>  
<hr>
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://myblob-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<hr>









</div>



</div>
</div>
<div class="col-sm-3 border" >

  <div>
	<h3 class='text-center '>Recent Posts</h3>	
	<hr>
	{% for obj in objects %}
	{% if forloop.counter0 < 5 %}
  <div class="breakWord narrow">
	<a href='{{ obj.get_absolute_url }}' style="color:#252617;">{{ obj.title }}</a>
	</div>
  <hr>
	{% endif %}
	{% endfor %}
	</div>
</div>
	
</div>


<!-- Card -->
{% endblock content %}

templates/blog/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %} CREATE  |  {{ block.super }}{% endblock head_title %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
<div class='thumbnail shadow-none p-3 mb-5 bg-light rounded text-center'>



<h1>Form</h1>
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form | crispy }}
<input type="submit" class="btn btn-default" name="">
</form>
</div>

<div class='card-body card-body-cascade col-sm-8 mx-auto'><h1 class="text-center">Preview</h1>


<div class="content-preview">
<h3 id="preview_title"></h3>
<div id="preview_content"></div>
</div>

</div>

</div>
{% endblock content %}

templates/blog/home.html
{% extends "base.html" %}

{% block content %}


<div class="row">
	
<div class="col-sm-6">

{% for obj in object %} 
<div class='ml-auto'>
<!-- Card -->
<div class="card h-50">

  <!-- Card image -->
  <div class="view overlay">
  	{% if obj.image %}
    <img class="card-img-top" src="{{ obj.image.url }}" alt="Card image cap">
    <a href="{{ obj.get_absolute_url }}">
      <div class="mask rgba-white-slight"></div>
    </a>
   
    {% endif %}
  </div>

  <!-- Card content -->
  <div class="card-body">

    <!-- Title -->
    <h4 class="card-title">{{ obj.title }}</h4>
    <!-- Text -->
    <div class="card-text rimage">{{ obj.get_markdown| truncatechars_html:400}}</div>
    <!-- Button -->
    <a href="{{ obj.get_absolute_url }}" class=""><strong>Read More...</strong></a>
    <hr>
    <p class="font-weight grey-text py-2"><i>Written by &nbsp </i><b>{{ obj.user.first_name}} {{ obj.user.last_name}} &nbsp|&nbsp </b><small> {{ obj.publish}}</small>
    {% if obj.draft %}<h2>Draft Post</h2>{% endif %}	</p>


  </div>
</div>
</div>
<hr>


{% endfor %}





<!--Pagination -->
<nav aria-label="pagination example">
    <ul class="pagination pagination-circle pg-blue mb-0">
{% if object.has_previous %}
        <!--First-->
        <li class="page-item"><a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">First</a></li>

        <!--Arrow left-->
        <li class="page-item">
            <a class="page-link" href="?{{page_request_var}}={{ object.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
{% endif %}
        <!--Numbers-->
         <span class="current">
        Page {{ object.number }} of {{ object.paginator.num_pages }}
</span>
 {% if object.has_next %}
        <!--Arrow right-->
        <li class="page-item">
            <a class="page-link" href='?{{page_request_var}}={{ object.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}' aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>

        <!--Last-->
        <li class="page-item"><a class="page-link" href="?page={{ object.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Last</a></li>
{% endif %}
    </ul>

</nav>

</div>








<div class="col-sm-6">

<h1>Tags</h1>
{% for obj in tags %}
<a href="{% url 'posts:tag_view' obj.tag %}" class="badge badge-primary">{{ obj.tag }}</a>
{% endfor %}
{% if user.is_authenticated %}
<hr>
<a href="{% url 'posts:create' %}" class="btn btn-default btn-lg active" role="button">CREATE POST</a>
{% endif %}
</div>
</div>



<!-- Card -->
{% endblock content %}

templates/blog/profile.html
<h1>{{ instance.user }}</h1>

templates/categories.html
{% extends 'base.html' %}
{% load static  %}

{% block head_title %} {{ instance.name }} {% endblock %}

{% block content %}
<br>
<div class="text-center"><h2>{{instance.name}}</h2></div>

{% if  instance.children.all %}
    <h4>Sub Categories</h4>
    {% for i in instance.children.all %}
        <a href="{{ i.slug }}"> {{ i.name }} </a><br>
    {% endfor %}

    <br><hr>
{% endif %}

{% if  instance.post_set.all %}
 {% for i in instance.post_set.all %}
  <h4>Posts</h4>
  <div class="row small-up-1 medium-up-3" >

   <div class="column">
    <a href="{{ i.slug }}">
      <div class="card" style="width: 300px; border-color: black">
         <div class="card-divider">
           <strong>{{ i.title | truncatechars:30}}</strong>
         </div>

         <div class="card-section">
          <small>{{ i.publish}} </small>
          <p>{{ i.content | safe | truncatechars_html:120 }}</p>
         </div>
      </div>
    </a>
   </div>
{% endfor %}

{% endif %}
</div>
{% endblock %}

templates/categoryhome.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for obj in objects %}

<a href="{{obj.get_absolute_url}}"> {{ obj.name }}
</a>
{% endfor %}


</body>
</html>